[package]
name = "leptos_image"
version = "0.2.0"
edition = "2021"
authors = ["Nico Burniske"]
description = "Static Image Optimizer for Leptos"
exclude = ["example/"]
keywords = ["leptos"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/nicoburniske/leptos-image"

[dependencies]
leptos = { version = "0.7.0-rc0", default-features = false }
leptos_router = { version = "0.7.0-rc0", default-features = false }
leptos_meta = { version = "0.7.0-rc0", default-features = false }

wasm-bindgen = "0.2"
web-sys = { version = "0.3", optional = true, features = ["HtmlImageElement"] }

tokio = { version = "1", features = [
    "rt-multi-thread",
    "rt",
    "fs",
], optional = true }
axum = { version = "0.7", optional = true, features = ["macros"] }
tower = { version = "0.5", optional = true }
tower-http = { version = "0.6", features = ["fs"], optional = true }

image = { version = "0.25", optional = true }
webp = { version = "0.3", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_qs = "0.13"
thiserror = { version = "1", optional = true }
base64 = "0.22"
tracing = { version = "0.1", optional = true }
dashmap = { version = "6", optional = true }

[features]
ssr = [
    "leptos_router/ssr",
    "leptos_meta/ssr",
    "leptos/ssr",
    "dep:webp",
    "dep:image",
    "dep:tokio",
    "dep:axum",
    "dep:tower",
    "dep:tower-http",
    "dep:tracing",
    "dep:dashmap",
    "dep:thiserror",
]
hydrate = ["dep:web-sys", "leptos/hydrate"]

[dev-dependencies]
leptos_axum = "0.7.0-rc0"
